sudo: required
dist: trusty
language: php
php:
  - "7.0"
install:
  - composer install
cache:
  directories:
    - $HOME/.composer 
    - vendor
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cd tests
  - sh ./init_fuseki.sh
  - cd ..
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - pkill -f 'java -Xmx1200M -jar'
addons:
  code_climate:
    repo_token: fb98170a5c7ea9cc2bbab19ff26268335e6a11a4f8267ca935e5e8ff4624886c
env:
  - FUSEKI_VERSION=3.4.0
  - FUSEKI_VERSION=SNAPSHOT
  - CC_TEST_REPORTER_ID=fb98170a5c7ea9cc2bbab19ff26268335e6a11a4f8267ca935e5e8ff4624886c
matrix:
  allow_failures:
  - env: FUSEKI_VERSION=SNAPSHOT
notifications:
    slack: finto:5rO9Lp4Tstn6y34grtFBpjJ0
